### ISSUE TITLE
Worldguard extension issue ?

### ISSUE THREAD

**Issue by MrMaleficus** [DenizenScript/Depenizen-For-Bukkit#103]
Hello, i want to report an issue.
When i break a block and log this action, this fires this error :
Using latest both Worldguard, Depenizen, and Denizen
```
[13:00:01 INFO]:  Starting InstantQueue 'LOG BREAK DIAMOND_TheirAstrologyPlace'... 
[13:00:01 INFO]:  Queue 'LOG BREAK DIAMOND_TheirAstrologyPlace' Executing: IF "<player.item_in_hand.enchantments.level[silk_touch]>" "==" "0" "&&" "w@MapEvent|w@Concours" "!contains" 
                   "<player.location.world>" "{" "-" "log" "<player.name> <&co> Minerai Diamant" "type:warning" "file:denizenlogs/minerais/test.log" "}" 
[13:00:01 INFO]: +- Executing dCommand: IF/p@MrMaleficus ---------+ 
[13:00:01 INFO]: +> Executing 'IF': use_braces='true' 
[13:00:01 INFO]:  Filled tag <player.item_in_hand.enchantments.level[silk_touch]> with '0'. 
[13:00:01 INFO]:  Comparable='Decimal(0.0)', Operator='EQUALS', ComparedTo='Decimal(0.0)' --> OUTCOME='true' 
[13:00:01 INFO]:  ERROR! Internal exception was thrown! 
[13:00:01 WARN]: java.lang.reflect.InvocationTargetException
[13:00:01 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:00:01 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[13:00:01 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:00:01 WARN]:        at java.lang.reflect.Method.invoke(Method.java:497)
[13:00:01 WARN]:        at net.aufdemrand.denizencore.objects.properties.PropertyParser.getProperties(PropertyParser.java:87)
[13:00:01 WARN]:        at net.aufdemrand.denizen.objects.dWorld.getAttribute(dWorld.java:766)
[13:00:01 WARN]:        at net.aufdemrand.denizen.objects.dLocation.getAttribute(dLocation.java:1524)
[13:00:01 WARN]:        at net.aufdemrand.denizen.objects.dEntity.getAttribute(dEntity.java:1859)
[13:00:01 WARN]:        at net.aufdemrand.denizen.objects.dPlayer.getAttribute(dPlayer.java:2047)
[13:00:01 WARN]:        at net.aufdemrand.denizen.tags.core.PlayerTags.playerTags(PlayerTags.java:90)
[13:00:01 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:00:01 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[13:00:01 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:00:01 WARN]:        at java.lang.reflect.Method.invoke(Method.java:497)
[13:00:01 WARN]:        at net.aufdemrand.denizencore.tags.TagManager.fireEvent(TagManager.java:83)
[13:00:01 WARN]:        at net.aufdemrand.denizencore.tags.TagManager$1.run(TagManager.java:258)
[13:00:01 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[13:00:01 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[13:00:01 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[13:00:01 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[13:00:01 WARN]:        at java.lang.Thread.run(Thread.java:745)
[13:00:01 WARN]: Caused by: java.lang.NullPointerException
[13:00:01 WARN]:        at com.sk89q.worldguard.bukkit.ConfigurationManager.get(ConfigurationManager.java:222)
[13:00:01 WARN]:        at com.sk89q.worldguard.bukkit.WorldGuardPlugin.getRegionManager(WorldGuardPlugin.java:972)
[13:00:01 WARN]:        at net.gnomeffinway.depenizen.extensions.worldguard.WorldGuardWorldExtension.<init>(WorldGuardWorldExtension.java:42)
[13:00:01 WARN]:        at net.gnomeffinway.depenizen.extensions.worldguard.WorldGuardWorldExtension.getFrom(WorldGuardWorldExtension.java:28)
[13:00:01 WARN]:        ... 21 more
[13:00:01 INFO]:  Filled tag <player.location.world> with 'w@world'. 
[13:00:01 INFO]:  Logic='NEGATIVE', Comparable='dList(li@w@MapEvent|w@Concours)', Operator='CONTAINS', ComparedTo='Element(w@world)' --> OUTCOME='true' 
[13:00:01 INFO]:  Queue 'LOG BREAK DIAMOND_TheirAstrologyPlace' Executing: LOG "<player.name> <&co> Minerai Diamant" "type:warning" "file:denizenlogs/minerais/test.log" 
[13:00:01 INFO]: +- Executing dCommand: LOG/p@MrMaleficus ---------+ 
[13:00:01 INFO]:  Filled tag <player.name> with 'MrMaleficus'. 
[13:00:01 INFO]:  Filled tag <&co> with ':'. 
[13:00:01 INFO]: +> Executing 'LOG': message='MrMaleficus : Minerai Diamant'  file='denizenlogs/minerais/test.log'  type='warning' 
[13:00:01 INFO]:  Completing queue 'LOG BREAK DIAMOND_TheirAstrologyPlace' in 19ms. 
```

**Comment by Fortifier42** [comment]
That's a worldguard issue, not Depenizen.

Are you even calling anything worldguard based? (Script pls)

**Comment by MrMaleficus** [comment]
I just call the break event.
Here the script :
```
"Log Break Diamond": 
  type: world
  debug: true
  events:
    on player breaks DIAMOND_ORE:  
    - if <player.item_in_hand.enchantments.level[silk_touch]> == 0 && 'w@MapEvent|w@Concours' !contains <player.location.world> {
       - log "<player.name> : Minerai Diamant" type:warning file:denizenlogs/minerais/<player.name>.log
    }
```

**Comment by Fortifier42** [comment]
Yeah - worldguard issue or incorrect versions of plugins.

**Comment by MrMaleficus** [comment]
i'll contact sq89 so, thank you for your quick answer !

**Comment by Fortifier42** [comment]
No worries, thanks for reporting :)

**Comment by MrMaleficus** [comment]
Maybe @mcmonkey4eva can look around ? After many testing it's look like it's the log command with the break event that don't work.
The log command with another event works fine
The break event with anther command works fine

**Comment by Fortifier42** [comment]
Not even sure how... they could be related

**Comment by Fortifier42** [comment]
We've found the issue. Fixing :)
