### ISSUE TITLE
Fail to load MythicMobs

### ISSUE THREAD

**Issue by Noiknez** [DenizenScript/Depenizen-For-Bukkit#113]
Greeting, with depenizen i got an mythicmobs error that failed to load on startup :
(depenizen logs) http://pastebin.com/nQK2QRf
Depenizen version : 321

**Comment by Morphan1** [comment]
That link has expired, please provide a new one.

**Comment by Noiknez** [comment]
New paste : http://pastebin.com/Uh3LJ16K

**Comment by mcmonkey4eva** [comment]
Please stop using the expiration feature of pastebin.

The relevant error is this:
```

[11:31:55] [Server thread/WARN]: java.lang.NoClassDefFoundError: net/elseland/xikage/MythicLib/Adapters/AbstractEntity
[11:31:55] [Server thread/WARN]:    at java.lang.Class.getDeclaredMethods0(Native Method)
[11:31:55] [Server thread/WARN]:    at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
[11:31:55] [Server thread/WARN]:    at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
[11:31:55] [Server thread/WARN]:    at java.lang.Class.getMethod0(Class.java:3018)
[11:31:55] [Server thread/WARN]:    at java.lang.Class.getMethod(Class.java:1784)
[11:31:55] [Server thread/WARN]:    at net.aufdemrand.denizencore.objects.ObjectFetcher.registerWithObjectFetcher(ObjectFetcher.java:76)
[11:31:55] [Server thread/WARN]:    at net.gnomeffinway.depenizen.support.SupportManager.register(SupportManager.java:39)
[11:31:55] [Server thread/WARN]:    at net.gnomeffinway.depenizen.support.Supported.set(Supported.java:61)
[11:31:55] [Server thread/WARN]:    at net.gnomeffinway.depenizen.support.Supported.setup(Supported.java:31)
[11:31:55] [Server thread/WARN]:    at net.gnomeffinway.depenizen.Depenizen.checkPlugins(Depenizen.java:63)
...
[11:31:55] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: net.elseland.xikage.MythicLib.Adapters.AbstractEntity
[11:31:55] [Server thread/WARN]:    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
```

Looks like version disagreement.

**Comment by Noiknez** [comment]
Should i see i the side of MythicMobs ? Or update something ?

**Comment by mcmonkey4eva** [comment]
Make sure you have the latest mythicmobs off of https://www.spigotmc.org/resources/mythicmobs.5702/

**Comment by Noiknez** [comment]
I got a devbuild version + the new MythicLib dependency (for version 4.5.0+)

**Comment by mcmonkey4eva** [comment]
Could you try the public Spigot release version, not the dev release?

It's possible they changed something that our code doesn't account for yet.

**Comment by Noiknez** [comment]
The public version of MythicMobs work fine (it dont need MythicLib). It is just a suggestion : could Depenizen be compatible with MythicLib that is already public ?

**Comment by mcmonkey4eva** [comment]
Not until a new public release of MythicMobs itself is available.

**Comment by Noiknez** [comment]
Ok, i will wait until then :+1:
