### ISSUE TITLE
Null pointer exception when using location tag on wilderness

### ISSUE THREAD

**Issue by Croat** [DenizenScript/Depenizen-For-Bukkit#46]
[19:01:27 INFO]: Cr0at issued server command: /ex narrate \<player.location.town||null\>
[19:01:27 INFO]:  Starting InstantQueue 'EXCOMMAND_AdvertisersSerumDx'... 
[19:01:27 INFO]:  Queue 'EXCOMMAND_AdvertisersSerumDx' Executing: NARRATE 
                   "<player.location.town||null>" 
[19:01:27 INFO]: +- Executing dCommand: NARRATE/p@Cr0at ---------+ 
[19:01:27 INFO]:  ERROR! Internal exception was thrown! 
[19:01:27 WARN]: java.lang.reflect.InvocationTargetException
[19:01:27 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:01:27 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[19:01:27 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:01:27 WARN]: 	at java.lang.reflect.Method.invoke(Method.java:606)
[19:01:27 WARN]: 	at net.aufdemrand.denizencore.tags.TagManager.fireEvent(TagManager.java:75)
[19:01:27 WARN]: 	at net.aufdemrand.denizencore.tags.TagManager.readSingleTag(TagManager.java:242)
[19:01:27 WARN]: 	at net.aufdemrand.denizencore.tags.TagManager.tag(TagManager.java:274)
[19:01:27 WARN]: 	at net.aufdemrand.denizencore.tags.TagManager.fillArguments(TagManager.java:323)
[19:01:27 WARN]: 	at net.aufdemrand.denizencore.scripts.commands.CommandExecuter.execute(CommandExecuter.java:203)
[19:01:27 WARN]: 	at net.aufdemrand.denizencore.scripts.queues.ScriptEngine.revolve(ScriptEngine.java:51)
[19:01:27 WARN]: 	at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.revolve(ScriptQueue.java:660)
[19:01:27 WARN]: 	at net.aufdemrand.denizencore.scripts.queues.core.InstantQueue.onStart(InstantQueue.java:53)
[19:01:27 WARN]: 	at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.start(ScriptQueue.java:519)
[19:01:27 WARN]: 	at net.aufdemrand.denizen.Denizen.onCommand(Denizen.java:1018)
[19:01:27 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[19:01:27 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[19:01:27 WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645)
[19:01:27 WARN]: 	at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115)
[19:01:27 WARN]: 	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950)
[19:01:27 WARN]: 	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26)
[19:01:27 WARN]: 	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53)
[19:01:27 WARN]: 	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
[19:01:27 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
[19:01:27 WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[19:01:27 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683)
[19:01:27 WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[19:01:27 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623)
[19:01:27 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526)
[19:01:27 WARN]: 	at java.lang.Thread.run(Thread.java:745)
[19:01:27 WARN]: Caused by: java.lang.NullPointerException
[19:01:27 WARN]: 	at com.palmergames.bukkit.util.NameValidation.filterName(NameValidation.java:122)
[19:01:27 WARN]: 	at com.palmergames.bukkit.util.NameValidation.checkAndFilterName(NameValidation.java:32)
[19:01:27 WARN]: 	at com.palmergames.bukkit.towny.db.TownyDatabaseHandler.getTown(TownyDatabaseHandler.java:133)
[19:01:27 WARN]: 	at net.gnomeffinway.depenizen.extensions.towny.TownyLocationExtension.getAttribute(TownyLocationExtension.java:56)
[19:01:27 WARN]: 	at net.aufdemrand.denizen.objects.dLocation.getAttribute(dLocation.java:1538)
[19:01:27 WARN]: 	at net.aufdemrand.denizen.objects.dEntity.getAttribute(dEntity.java:1617)
[19:01:27 WARN]: 	at net.aufdemrand.denizen.objects.dPlayer.getAttribute(dPlayer.java:1674)
[19:01:27 WARN]: 	at net.aufdemrand.denizen.tags.core.PlayerTags.playerTags(PlayerTags.java:79)
[19:01:27 WARN]: 	... 29 more
[19:01:27 INFO]:  Filled tag <player.location.town||null> with 'null'. 
[19:01:27 INFO]: +> Executing 'NARRATE': Narrating='null'  Targets='[p@Cr0at]' 
[19:01:27 INFO]:  Completing queue 'EXCOMMAND_AdvertisersSerumDx' in 5ms.

**Comment by mcmonkey4eva** [comment]
That looks like a Towny error rather than one on our side... maybe @Morphan1 can find the issue in their code and submit a PR though :D

**Comment by mcmonkey4eva** [comment]
Actually it's an error on our end. Fixed!
